### ISSUE TITLE
Key word glitches?

### ISSUE THREAD

**Issue by arlocsherman** [CenterOnBudget/getcensus#16]
Not urgent but is anyone else having trouble with these three key words: snap, costburden_renters, costburden_owners?  On my machine, calling them (eg "getcensus snap, clear") returns the error "server refused to send file   could not open url".   
{And a separate, almost opposite kind of issue: the key word "housing_overview" returns data -- LOTS of data. Stata says over 1,000 variables worth.  Maybe the name of the key word should be housing_compendium rather than housing_overview?!  :)  }  THANK YOU.

**Comment by c-zippel** [comment]
The trouble with snap is known (issue #10) but the problems with costburden_ are new. Ergh. I will check it out.

**Comment by c-zippel** [comment]
@arlocsherman FYI this is fixed! see PR #19
