### ISSUE TITLE
Add keyword "povertyratio"?

### ISSUE THREAD

**Issue by arlocsherman** [CenterOnBudget/getcensus#21]
Low urgency.  Should we add one or more keywords on poverty_ratio (or "ratio" or "povratio")?  State groups and policy folks very often need detailed data on ratio of income to poverty.  One overall (B17002?); maybe another for characteristics (S1703 and/or the little-known table B05010 with children by nativity relevant to federal and state EITC projections, immigrant exclusions, etc.)?

**Comment by c-zippel** [comment]
This should be easy to do. Table B05010 is already a keyword: `kids_pov_parents_nativity`.
