### ISSUE TITLE
Test dialog box

### ISSUE THREAD

**Issue by c-zippel** [CenterOnBudget/getcensus#49]

**Comment by lzak88** [comment]
Mostly, the dialog box works great. I had one issue and one suggestion.

Issue: Is the "Browse retrieved data in the data editor" button supposed to open the data table automatically upon running the query? It doesn't do that for me. All the other buttons at the bottom of the dialog box are working.

Suggestion: Is there a way to add a button that adds the "clear" command to the end of the query so you don't have to remember to clear what you've called prior before opening the dialog box and pulling your next query? There is something similar already that adds replace to the end of a query when you want to save a file over an existing one, so I'm thinking adding a clear button wouldn't be too difficult?
