### ISSUE TITLE
error message "variable state not found r(111);" after any 

### ISSUE THREAD

**Issue by martinjbraun** [CenterOnBudget/getcensus#55]
**Describe the bug**
Any time I use this command I get the same error message "variable state not found r(111);"

**To Reproduce**
getcensus S1701_C02_001 S1701_C03_001, years(2015/2019) statefips(51) clear 
Output is : 

"(1 var, 14 obs)
 Link to data for 2015
(1 var, 14 obs)
 Link to data for 2016
(1 var, 14 obs)
 Link to data for 2017
(1 var, 14 obs)
 Link to data for 2018
(1 var, 14 obs)
 Link to data for 2019
variable state not found
r(111);"

Stata version 17.0 SE running on UNIX server

**Expected behavior**
I got this example off of  statlist https://www.statalist.org/forums/forum/general-stata-discussion/general/1632583-new-package-getcensus-on-ssc-load-american-community-survey-data-from-the-census-bureau-api-into-stata
 
and expect it to: "Load ACS variables S1701_C02_001 (population in poverty) and S1701_C03_001 (poverty rate) for the state of Virginia (FIPS code 51) for the most recent five years"

I get the same error message any time I run a getcensus command

**Notes*
It looks like someone else  mentioned this problem on statlist, but  I don't see a solution. This command would be amazing if it works! Thanks!

**Comment by martinjbraun** [comment]
[getcensus.log](https://github.com/CenterOnBudget/getcensus/files/8474298/getcensus.log)

Here is my log. I replaced my actual census key with "\~censuskey\~"

**Comment by martinjbraun** [comment]
I ran the same code on Windows and am getting the same error. See the log attached.

[getcensus_windows.log](https://github.com/CenterOnBudget/getcensus/files/8475756/getcensus_windows.log)
.

**Comment by c-zippel** [comment]
Thanks for the additional info. Not an OS issue then. When you click the link "Link to data for 2015" or any of the other years, do you see a message about an invalid API key?

**Comment by martinjbraun** [comment]
Yes! I never clicked "click here to activate your key" when I requested the API key.  Everything works now that I have a valid API key. Sorry for the trouble!

**Comment by c-zippel** [comment]
No worries! This was a useful exercise. Now I know that getcensus will not throw a useful error if the API key is invalid. I'll aim to fix that in the next version.
