### ISSUE TITLE
Make API key optional

### ISSUE THREAD

**Issue by c-zippel** [CenterOnBudget/getcensus#62]
Following [tidycensus v 1.3](https://walker-data.com/tidycensus/news/index.html#tidycensus-13). Max daily queries without a key is 500

**Comment by shingtgen** [comment]
I commented out my API key in my profile.do and then ran:
`getcensus S2001_C01_001, sample(5) clear`

I got the following message:
> You have not provided an API key. Without a key, you are limited to 500 API queries per day.
> To use an API key, specify key() or store your API key in a global macro named _censuskey_ in
> your profile.do.


Looks good!

Separately, I checked the documentation for the `key()` option just for fun and spotted the tiniest thing you might want to fix while you're updating--an extra space after the URL and before the period here:
>     key(string) specifies your Census Bureau API key. If you do not have an API key, you may acquire at
>         https://api.census.gov/data/key_signup.html .

**Comment by c-zippel** [comment]
Thanks! I've fixed the extra space in 1af2ec9.
