### ISSUE TITLE
Unable to access 2018-2022 ACS 5-year estimates  tables 

### ISSUE THREAD

**Issue by drblanchwright** [CenterOnBudget/getcensus#69]
### Bug description

Hello, 

I am trying to download 5-year 2018-2022 table estimates from ACS, which were released 12/7/23. I am obtaining the following error messages about updating getcensus; when I try to update, it says invalid syntax. I saw on the getcensus website that updating getcensus won't be necessary for new data releases. I am unsure how to proceed. Thank you in advance. 

'''
 getcensus S2201, sample(5) year(2022) geography(tract) statefips(06) countyfips(037)
Cannot fetch 5-year ACS estimates for 2022.
This may be because:
    • You need to update getcensus. To update, run ado update getcensus, update.
    • The 2022 5-year estimates have not yet been released. Check the ACS data release page on the Census Bureau
        website.

. 
. ado update getcensus, update
invalid syntax
r(198);
'''

### Operating system

Mac OS X

### getcensus version

- [X] I'm using the lastest version of getcensus.

**Comment by c-zippel** [comment]
Right, starting with getcensus version 2.1.4, there is no need to update the package for each new data release -- but it looks like you do not have version 2.1.4 because you were unable to update getcensus. `ado update getcensus, update` should not throw a syntax error. Would you please try running `ado update getcensus, update` again, exactly as written?

**Comment by drblanchwright** [comment]
This is what I get back: 

. ado update getcensus, update
invalid syntax
r(198);


I am using Stata/IC 15.1. Not sure if that matters. On the getcensus website it says, "getcensus requires Stata version 13.1 or later."

**Comment by c-zippel** [comment]
`ado update` is a Stata command, not a getcensus command, and I'm unable to replicate your error, so I'm going to go ahead and close this issue.

You might want to check if you can update your other SSC packages, rerun `ado update` in [debug mode](https://www.stata.com/support/faqs/programming/debugging-program/), ask for help on Statalist, and/or uninstall and reinstall getcensus with:
```
ado uninstall getcensus
ssc install getcensus
```

Good luck!
